### ISSUE TITLE
Implement SLCosmo.compute_the_joint_log_likelihood to do the actual calculation.

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/SLCosmo#15]
The existing method has [pseudocode for this](https://github.com/DarkEnergyScienceCollaboration/SLCosmo/blob/master/python/desc/slcosmo/SLCosmo.py#L130).

**Comment by drphilmarshall** [comment]
@tcollett fixed this in #20 at the hack day :-)
