### ISSUE TITLE
Should the Round Trip test be added as a `unittest`?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLCosmo#22]
I think it should, despite not really being a "unit test". It will need a fuzzy equals operator, because we can only ask for the posterior mean H0 to be equal to the truth "within the uncertainty". Would I want the test to pass if the recovered H0 was 3 sigma away from the truth? Do I need to do an large set of Round Trips to build up statistics? Hmm. Thoughts welcome.

**Comment by drphilmarshall** [comment]
I implemented the round-trip as a "science test", in #25 - I think it will have made our coverage go up, so I can't think why we would not do this kind of thing if it was easy (like it is in this case). Closing out unopposed! :-)

**Comment by jchiang87** [comment]
I think this sort of thing is perfectly reasonable, especially since it runs fairly quickly.  It is nonetheless still useful to have more granular unit tests so that any failures introduced by new code are localized right away.
