### ISSUE TITLE
Travis needs to install `lapack` before `scipy`

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLCosmo#27]
As described [here](http://danielnouri.org/notes/2012/11/23/use-apt-get-to-install-python-dependencies-for-travis-ci/), perhaps?

**Comment by jchiang87** [comment]
The consensus seems to be that using `conda` to install `scipy` is preferred because of all of `scipy`'s dependencies.   So I've done that in #8, and travis-ci seems [happy](https://travis-ci.org/DarkEnergyScienceCollaboration/SLCosmo/builds/147500278).

**Comment by drphilmarshall** [comment]
Great! Thank you :-)

**Comment by drphilmarshall** [comment]
Closed during #8
