### ISSUE TITLE
Use cases for writing unit tests

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/SLCosmo#3]
Hey @drphilmarshall!  It would be great if we could start off with use cases to guide the writing of the unit tests for this code.  One way to start might be to write pseudocode illustrating how you would like to use the classes, methods, and functions in this package in a number of different contexts, e.g., reading in data, doing intermediate or diagnostic calculations, making plots, writing output files, etc..

**Comment by drphilmarshall** [comment]
Fixed in #5 !
