### ISSUE TITLE
Upgrade read_in_from() method to get Fermat potential differences from header 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLCosmo#30]
This functionality is inexplicably missing at the moment, sadly. This issue can be closed when the RoundTrip notebook writes out mock data to file and then reads it back in.

**Comment by jchiang87** [comment]
Hey @drphilmarshall, 

Isn't [this](https://github.com/DarkEnergyScienceCollaboration/SLCosmo/blob/master/python/desc/slcosmo/TDC2.py#L78) what you want for this issue?  I had also added some [tests](https://github.com/DarkEnergyScienceCollaboration/SLCosmo/blob/master/tests/test_TDC2ensemble.py#L50) that exercise the round trip with `.write_out_to`.

**Comment by drphilmarshall** [comment]
Whoah! Where did that come from? :-) I must have been looking at a fork/branch, somehow, sorry. I'll update the RoundTrip notebook and Science test to write out and read in data, and then close this out. Thanks Jim - really nice work :-)
