### ISSUE TITLE
Cannot add repo in Coveralls

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLCosmo#6]
SLCosmo does not appear in Coveralls' [list of DESC repos](https://coveralls.io/repos/new?name=DarkEnergyScienceCollaboration&service=github). I wonder why it is not being picked up? I issued this at Coveralls too, speculating that 70 public repos might be the limit for an organization... but maybe I am doing something wrong?

**Comment by jchiang87** [comment]
I was able to get it to appear on the Coveralls `ADD REPOS` page by clicking the `RE-AUTHORIZE WITH GITHUB` button at the bottom of that page.

**Comment by drphilmarshall** [comment]
Aha! I will remember that. Thanks Jim!
