### ISSUE TITLE
Re-implement TDC2ensemble.read_in_from as static factory method

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/SLCosmo#9]
This seems like it would be better suited as a static method that read in a file and returned a `TDC2ensemble` object.  This avoids creating an object and changing its internal state to read in the data.  Add tests for reading in the expected TDC2 file formats and test for expected attributes that should be ascertained from the file header info.  Also, add appropriate data to use in the tests.

**Comment by drphilmarshall** [comment]
Done! As part of #8 . Thanks @jchiang87 :-)
